- name: wait for 2 sec and continue play
  wait_for:
      timeout: 2
      
      
- name: Check all port
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 2
    timeout: 3
  ignore_unreachable: yes
  ignore_errors: yes
  register: port_out
  #delegate_to: localhost
  #tags: port_check

- debug:
    var: port_out     

- name: Connection Failed Status
  debug:
    msg: "{{inventory_hostname}} is not Reachable"
  when: port_out.failed == true
  tags: port_check
  ignore_errors: yes


- name: Connection Success status
  debug:
    msg: "{{ inventory_hostname }} is reachable"
  when: port_out.failed == false
  tags: port_check
  ignore_errors: yes
  
  
  
- name: Include for each server in group linux
  include: health_check.yml
  with_items: "{{ inventory_hostname }}"
  when: port_out.failed == false
  ignore_errors: yes
  
  
- stat: path=/var/lib/jenkins/workspace/Wait_for/wait_for/reports/Server_Health_Check.html
  register: st
- template:
    src: /var/lib/jenkins/workspace/Wait_for/wait_for/Playbooks/wait/templates/healthcheck.j2
    dest: /var/lib/jenkins/workspace/Wait_for/wait_for/reports/Server_Health_Check.html
  when: not st.stat.exists  
  ignore_errors: yes 
  

  
