pipeline {
   
    agent any
  
          stages {
            
               stage ('wait_for') {
                 
                    steps {
                       sh 'ansible-playbook /var/lib/jenkins/workspace/${JOB_NAME}/wait_for/Playboooks/wait.yml'
                      
                    }
               }
          }
}
 
