---

- name: Restarting Linux services
  hosts: linux
  gather_facts: false
  become: true
  become_user: true
  become_method: sudo
  vars_files:
      - /ansible_playbooks/sravsautomation/configuration/groupvars/linux
  roles:
    - restart
